In [28]:
import numpy as np

In [29]:
arr = np.random.randint(1,10,size = (2,2))
arr

array([[2, 2],
       [1, 2]], dtype=int32)

In [30]:
np.savetxt('arr.txt',arr)

In [31]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is F294-1CD1

 Directory of C:\Users\muhasebe\Desktop\Notebooks

06.01.2025  19:12    <DIR>          .
06.01.2025  19:12    <DIR>          ..
06.01.2025  18:46    <DIR>          .ipynb_checkpoints
06.01.2025  19:13               102 arr.txt
06.01.2025  19:12             8.297 numpy giriŸ.ipynb
17.12.2024  17:49             1.199 Untitled.ipynb
17.12.2024  20:45             4.007 Untitled1.ipynb
               4 File(s)         13.605 bytes
               3 Dir(s)  117.529.911.296 bytes free


In [32]:
arr2 = np.loadtxt('arr.txt')
arr2

array([[2., 2.],
       [1., 2.]])

In [33]:
np.savetxt('arr.txt',arr)

In [34]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is F294-1CD1

 Directory of C:\Users\muhasebe\Desktop\Notebooks

06.01.2025  19:12    <DIR>          .
06.01.2025  19:12    <DIR>          ..
06.01.2025  18:46    <DIR>          .ipynb_checkpoints
06.01.2025  19:13               102 arr.txt
06.01.2025  19:12             8.297 numpy giriŸ.ipynb
17.12.2024  17:49             1.199 Untitled.ipynb
17.12.2024  20:45             4.007 Untitled1.ipynb
               4 File(s)         13.605 bytes
               3 Dir(s)  117.529.911.296 bytes free


In [35]:
arr2 = np.loadtxt('arr.txt')
arr2

array([[2., 2.],
       [1., 2.]])

In [38]:
a,b,c = np.random.randint(1,10,size = (3,2,2))
a,b,c

(array([[3, 4],
        [1, 8]], dtype=int32),
 array([[2, 3],
        [8, 7]], dtype=int32),
 array([[6, 3],
        [8, 1]], dtype=int32))

In [40]:
np.savez ('arrayler.npz',a,b,c)

In [41]:
npz = np.load('arrayler.npz')

npz['arr_0'],npz['arr_1'],npz['arr_2']

(array([[3, 4],
        [1, 8]], dtype=int32),
 array([[2, 3],
        [8, 7]], dtype=int32),
 array([[6, 3],
        [8, 1]], dtype=int32))

In [ ]:
for i in npz:
    